### PR TITLE
Join Our Team

### PR DESCRIPTION
**Pull request by willbarkoff**

### CODE REVIEW

**Comment by willbarkoff** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Does it work when I merge pull requests?

**Comment by willbarkoff** [comment]
@thatoddmailbox?

**Comment by thatoddmailbox** [comment]
@nywillb yes, but plox test it first! Also the [live site](https://planhub.me) won't automagically update unless I poke the server.

**Comment by willbarkoff** [comment]
Please poke!

**Pull request merged**
