### PR TITLE
Again testing system

### PR DESCRIPTION
**Pull request by thatoddmailbox**

### CODE REVIEW

**Comment by thatoddmailbox** [comment]
IT WORKED YAY

**Comment by medensqui** [comment]
@thatoddmailbox YAY. SO NOW DOES IT AUTOMAGICALLY UPDATE?

**Comment by thatoddmailbox** [comment]
When it's merged on stable.

**Comment by thatoddmailbox** [comment]
(pls don't break it)

**Comment by medensqui** [comment]
@thatoddmailbox yay
English pls?

**Comment by medensqui** [comment]
@thatoddmailbox So do I have to commit on master and merge to stable?

**Comment by thatoddmailbox** [comment]
@medensqui When you put things on the stable branch, the server automagically updates with it. Don't break things!

If you push to master (not the stable branch) it ignores it.

**Comment by thatoddmailbox** [comment]
@medensqui Yes.

**Pull request merged**
