### PR TITLE
Add all the stuffs

### PR DESCRIPTION
**Pull request by medensqui**
? Can I do dis

### CODE REVIEW

**Comment by thatoddmailbox** [comment]
@medensqui hold on and let me poke the db to allow prefs.

**Comment by medensqui** [comment]
@thatoddmailbox yay

**Comment by medensqui** [comment]
@thatoddmailbox Umm...where's the pref page?

**Comment by thatoddmailbox** [comment]
@medensqui still hidden away, use `setPage("prefs");`

**Comment by medensqui** [comment]
@thatoddmailbox Ok. It doesn't really do much. Where is the commit that allows for people to change their name? Also, is staging available to the public?

**Comment by thatoddmailbox** [comment]
@medensqui staging _is_ publicly available, and the name-changing was done with many commits.

**Pull request merged**
