### PR TITLE
#13

### PR DESCRIPTION
**Pull request by thatoddmailbox**

### CODE REVIEW

**Comment by medensqui** [comment]
@thatoddmailbox did it work?

**Comment by thatoddmailbox** [comment]
No.

**Comment by medensqui** [comment]
@thatoddmailbox GODDAMIT STUDER. JK :+1:

**Comment by thatoddmailbox** [comment]
@medensqui :wink:

Instead it broke the planner and left it "Loading...".

:stuck_out_tongue_closed_eyes:

**Comment by medensqui** [comment]
@thatoddmailbox NOT AGAIN

**Comment by thatoddmailbox** [comment]
@medensqui Why do you think I reverted it? :wink:^(∞)

**Pull request merged**
