### PR TITLE
Try to make the server wake up

### PR DESCRIPTION
**Pull request by thatoddmailbox**

### CODE REVIEW

**Comment by medensqui** [comment]
@thatoddmailbox STUDER WHAT DID YOU DO

**Comment by thatoddmailbox** [comment]
@medensqui oh no what broke

**Comment by medensqui** [comment]
@thatoddmailbox No just the title scared me

**Comment by thatoddmailbox** [comment]
@medensqui oh. Well, you see, the server was tired. so it went to sleep. now I have to poke it so it can wake up.

**Comment by medensqui** [comment]
@thatoddmailbox ah ok

**Comment by thatoddmailbox** [comment]
@medensqui trust me, I'm a serverologist

**Comment by thatoddmailbox** [comment]
@medensqui OK SERIOUSLY

THE SERVER HAD A MERGE CONFLICT

A MERGE CONFLICT

DESPITE NOT CHANGING ANYTHING

HOW DOES THIS WORK

WHY

**Comment by thatoddmailbox** [comment]
@medensqui ok wait I broke it for real now

:(

**Comment by medensqui** [comment]
@thatoddmailbox :(

**Comment by thatoddmailbox** [comment]
@medensqui wait no why isn't it working...

**Comment by medensqui** [comment]
@thatoddmailbox Idk. Also I gtg to bed now.

I'll see what you've done (or haven't done) in the morning

**Comment by thatoddmailbox** [comment]
@medensqui Ok!

**Comment by thatoddmailbox** [comment]
@medensqui Look at the end of #13

**Pull request merged**
