### PR TITLE
Fix live chat.

### PR DESCRIPTION
**Pull request by willbarkoff**

### CODE REVIEW

**Comment by willbarkoff** [comment]
@thatoddmailbox Are there any problems with this code?

**Comment by thatoddmailbox** [comment]
@nywillb umm.. There is some unfinished stuff, but it doesn't have an effect on normal use. We still should do some more testing before merge, though. There are a lot of commits...

**Comment by willbarkoff** [comment]
@thatoddmailbox Have you poked?

**Comment by thatoddmailbox** [comment]
@nywillb Yes. (but don't respond to the feedback because @RobotXLabs should since he sent the first message)

**Pull request merged**
