### PR TITLE
Testing stable/master system

### PR DESCRIPTION
**Pull request by thatoddmailbox**

### CODE REVIEW

**Comment by medensqui** [comment]
Did it work?

**Comment by medensqui** [comment]
@thatoddmailbox

**Comment by thatoddmailbox** [comment]
I think. I just need to do one last thing...

**Comment by medensqui** [comment]
@thatoddmailbox Ok. So we will only commit stable features?

**Comment by thatoddmailbox** [comment]
@medensqui I think. We could have a staging.planhub.me for the latest, beta stuff.

gtg now

**Comment by medensqui** [comment]
@thatoddmailbox K bye

**Comment by thatoddmailbox** [comment]
@medensqui IT WORKED

**Pull request merged**
