### PR TITLE
TRIED TO FIX SOMETHING THAT LOOKED BAD

### PR DESCRIPTION
**Pull request by willweinstein**
NO IDEA IF THIS WORKS, PLS CONFIRM

### CODE REVIEW

**Comment by thatoddmailbox** [comment]
@willweinstein THIS DOESN'T WORK :sob: IT TRIES TO APPEND TO A LIST WITH A CLASS OF `hwView-`

**Comment by willweinstein** [comment]
@thatoddmailbox SHHHHHH

**Comment by willweinstein** [comment]
@thatoddmailbox IDK HOW TO DO IT BUT DO YOU SEE WHAT I WAS TRYING TO DO?

**Comment by willweinstein** [comment]
@thatoddmailbox I DONT LIKETHE ORDER OF SOMETHING SO I TRIED TO CHANGE IT, PLS CHANGE IT

**Comment by thatoddmailbox** [comment]
@nywillb THIS IS BROKEN WHY WOULD YOU MERGE IT

**Pull request merged**
