### PR TITLE
by popular request

### PR DESCRIPTION
**Pull request by thatoddmailbox**

### CODE REVIEW

**Comment by medensqui** [comment]
@thatoddmailbox IS THIS THE HEX SPINNY THING

**Comment by thatoddmailbox** [comment]
@medensqui no, it makes it so when you type an event with tag "hex" it turns green on black text.

**Comment by medensqui** [comment]
@thatoddmailbox HEX SPINNY

**Comment by thatoddmailbox** [comment]
@medensqui HOW TRIGGER

**Comment by medensqui** [comment]
@thatoddmailbox THE HEX BACKGROUND THINGY DOESNT WORK

**Comment by thatoddmailbox** [comment]
@medensqui IT WORKS FOR ME AND WILL W WHYYYYYY

You have to make an event with the tag of "hex" (instead of HW or Test or whatever)

**Pull request merged**
